title: "RASTREO"
# Descripción corta para SEO y redes sociales
description: "Brigada Robotizada de Búsqueda y Rescate. Proyecto Beca Leonardo 2024 Fundación BBVA."

# --- CONFIGURACIÓN DE URL ---
# Es vital que url NO tenga barra al final y baseurl SÍ tenga barra al inicio
url: "https://christyancruz11.github.io"
baseurl: "/rastreo"

# Idioma
lang: "es"
locale: "es-ES"

# --- TEMA Y APARIENCIA ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # Nombre correcto de la variable para el color

# --- PLUGINS ---
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# --- COMPORTAMIENTO ---
search: true
words_per_minute: 200
comments: false

# --- VALORES POR DEFECTO (MUY IMPORTANTE) ---
# Esto asegura que todas las páginas nuevas tengan el diseño correcto
defaults:
  # Para todas las páginas y posts
  - scope:
      path: ""
    values:
      image: /assets/img/leonardo_1.jpeg # Imagen por defecto si no pones una
      layout: single        # Diseño estándar para páginas
      author_profile: false # Oculta la barra lateral de autor por defecto (actívala en las páginas que quieras)
      share: true

# --- PIE DE PÁGINA (FOOTER) ---
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ChristyanCruz11/rastreo"
  content: >
    <small>
    “Proyecto realizado con la Beca Leonardo de Investigación Científica y Creación Cultural 2024 de la Fundación BBVA”.<br>
    “La Fundación no se responsabiliza de las opiniones, comentarios y contenidos incluidos en el proyecto, los cuales son total y absoluta responsabilidad de sus autores”.
    </small>

# Configuración Sass
sass:
  style: compressed
include:
  - _pages
