title: RASTREO — Brigada Robotizada de Búsqueda y Rescate
description: Proyecto realizado con la Beca Leonardo de Investigación Científica y Creación Cultural 2024 de la Fundación BBVA.
url: https://christyancruz11.github.io
baseurl: /rastreo
lang: es
locale: es-ES

# Tema Minimal Mistakes vía remote_theme (compatible con GitHub Pages)
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Plugins soportados por GitHub Pages (no añadir otros)
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# Apariencia: probamos skin "air" (con acento azul)
theme_skin: air
search: true

# Navegación superior (asegura que "Equipo" está)

nav:
  - title: "Inicio"
    url: /
  - title: "Proyecto"
    url: /proyecto/
  - title: "Resultados"
    url: /resultados/
  - title: "Difusión"
    url: /difusion/
  - title: "Equipo"
    url: /equipo/
  - title: "Datos y Código"
    url: /datos-codigo/
  - title: "Contacto"
    url: /contacto/


# Footer con menciones BBVA (seguirá saliendo el badge flotante en index)
footer:
  content: >
    <small>
    “Proyecto realizado con la Beca Leonardo de Investigación Científica y Creación Cultural 2024 de la Fundación BBVA”.<br>
    “La Fundación no se responsabiliza de las opiniones, comentarios y contenidos incluidos en el proyecto, los cuales son total y absoluta responsabilidad de sus autores”.
    </small>

# (Opcional) compilar Sass y permitir assets/css
sass:
  style: compressed
include:
  - assets/css
